import { gunzipSync } from 'node:zlib';
import { NextResponse } from 'next/server';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
const BASE = 'https://opendata.ndw.nu';
const BBOX = { minLat: 51.895, maxLat: 51.94, minLon: 4.55, maxLon: 4.64 };
type Site = { id:string; name:string; coordinates:[number,number][]; road?:string };
type Reading = { speed?:number; travelTime?:number; time?:string };
let siteCache:{at:number;sites:Site[]}|null=null;
async function gz(name:string){const r=await fetch(`${BASE}/${name}`,{cache:'no-store',headers:{'User-Agent':'KIO-Nu/14 (+https://kio-nu.vercel.app)'}});if(!r.ok)throw new Error(`${name}: ${r.status}`);return gunzipSync(Buffer.from(await r.arrayBuffer())).toString('utf8');}
function textBetween(xml:string,tag:string){const m=xml.match(new RegExp(`<(?:\\w+:)?${tag}[^>]*>([\\s\\S]*?)<\\/(?:\\w+:)?${tag}>`,'i'));return m?.[1]?.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function numberBetween(xml:string,tags:string[]){for(const tag of tags){const v=Number(textBetween(xml,tag));if(Number.isFinite(v))return v;}return undefined;}
function records(xml:string,tag:string){return [...xml.matchAll(new RegExp(`<(?:\\w+:)?${tag}\\b([^>]*)>([\\s\\S]*?)<\\/(?:\\w+:)?${tag}>`,'gi'))].map(m=>({attrs:m[1],body:m[2]}));}
function attr(attrs:string,name:string){return attrs.match(new RegExp(`(?:^|\\s)${name}=["']([^"']+)["']`,'i'))?.[1];}
function parseSites(xml:string):Site[]{const out:Site[]=[];for(const r of records(xml,'measurementSiteRecord')){const id=attr(r.attrs,'id');if(!id)continue;const lats=[...r.body.matchAll(/<(?:\w+:)?latitude[^>]*>(-?\d+(?:\.\d+)?)<\/(?:\w+:)?latitude>/gi)].map(m=>Number(m[1]));const lons=[...r.body.matchAll(/<(?:\w+:)?longitude[^>]*>(-?\d+(?:\.\d+)?)<\/(?:\w+:)?longitude>/gi)].map(m=>Number(m[1]));const coordinates:[number,number][]=[];for(let i=0;i<Math.min(lats.length,lons.length);i++)if(lats[i]>=BBOX.minLat&&lats[i]<=BBOX.maxLat&&lons[i]>=BBOX.minLon&&lons[i]<=BBOX.maxLon)coordinates.push([lats[i],lons[i]]);if(!coordinates.length)continue;const name=textBetween(r.body,'measurementSiteName')||id;const road=textBetween(r.body,'roadName')||textBetween(r.body,'roadNumber');out.push({id,name,coordinates,road});}return out;}
function parseReadings(xml:string):Map<string,Reading>{const map=new Map<string,Reading>();for(const r of records(xml,'siteMeasurements')){const ref=r.body.match(/<(?:\w+:)?measurementSiteReference\b[^>]*id=["']([^"']+)["']/i)?.[1]||r.body.match(/<(?:\w+:)?measurementSiteReference[^>]*>([^<]+)</i)?.[1];if(!ref)continue;const speed=numberBetween(r.body,['speedValue','averageVehicleSpeed','vehicleSpeed']);const travelTime=numberBetween(r.body,['travelTime','travelTimeValue']);const time=textBetween(r.body,'measurementTimeDefault')||textBetween(r.body,'measurementTime');const current=map.get(ref)||{};if(speed!==undefined)current.speed=speed;if(travelTime!==undefined)current.travelTime=travelTime;if(time)current.time=time;map.set(ref,current);}return map;}
function status(speed?:number):'groen'|'oranje'|'rood'|'onbekend'{if(speed===undefined)return'onbekend';if(speed<20)return'rood';if(speed<40)return'oranje';return'groen';}
export async function GET(){try{let sites:Site[];if(siteCache&&Date.now()-siteCache.at<6*60*60*1000)sites=siteCache.sites;else{sites=parseSites(await gz('measurement_current.xml.gz'));siteCache={at:Date.now(),sites};}const [speedXml,timeXml]=await Promise.all([gz('trafficspeed.xml.gz'),gz('traveltime.xml.gz')]);const speed=parseReadings(speedXml),times=parseReadings(timeXml);const features=sites.map(s=>{const reading={...(times.get(s.id)||{}),...(speed.get(s.id)||{})};return{id:s.id,name:s.name,road:s.road||null,coordinates:s.coordinates,speedKmh:reading.speed??null,travelTimeSeconds:reading.travelTime??null,measurementTime:reading.time??null,status:status(reading.speed)};}).filter(f=>f.speedKmh!==null||f.travelTimeSeconds!==null);return NextResponse.json({updatedAt:new Date().toISOString(),source:'NDW Open Data',bbox:BBOX,features},{headers:{'Cache-Control':'public, s-maxage=45, stale-while-revalidate=120'}});}catch(e){return NextResponse.json({updatedAt:new Date().toISOString(),source:'NDW Open Data',features:[],error:e instanceof Error?e.message:'Onbekende fout'},{status:502});}}
