'use client';
import { Fragment, useEffect } from 'react';
import { MapContainer, TileLayer, CircleMarker, Polyline, Tooltip, ZoomControl, useMap, Marker } from 'react-leaflet';
import { DivIcon } from 'leaflet';
import type { Corridor, CorridorStatus } from './corridors';
type LiveCorridor=Corridor&{status:CorridorStatus;delayMinutes:number|null;message:string;details:string[]};
const colors:Record<CorridorStatus,string>={groen:'#16a565',oranje:'#ef8d24',rood:'#dc3f43',onbekend:'#8f9b95'};
function Focus({item}:{item:LiveCorridor|null}){const map=useMap();useEffect(()=>{if(item)map.flyTo(item.id.startsWith('algera')?[51.91461,4.58426]:item.point,item.id.startsWith('algera')?16:14,{duration:.7})},[item,map]);return null}
function algeraIcon(items:LiveCorridor[]){const main=items.find(i=>i.id==='algera-main');const bike=items.find(i=>i.id==='algera-bike');const lane=items.find(i=>i.id==='algera-lane');const dot=(x:LiveCorridor|undefined,txt:string,cls='')=>`<span class="clusterDot ${cls}" style="background:${colors[x?.status??'onbekend']}">${txt}</span>`;return new DivIcon({className:'algeraClusterWrap',html:`<div class="algeraCluster">${dot(main,'','center')}${dot(bike,'🚲','bike')}${dot(main,'🚗','car')}${dot(lane,'⇄','lane')}</div>`,iconSize:[88,88],iconAnchor:[44,44]});}
export default function MapView({items,selected,onSelect}:{items:LiveCorridor[];selected:LiveCorridor|null;onSelect:(item:LiveCorridor)=>void}){const algera=items.filter(i=>i.id.startsWith('algera'));const others=items.filter(i=>!i.id.startsWith('algera'));return <MapContainer center={[51.923,4.648]} zoom={11} minZoom={10} maxZoom={18} zoomControl={false} className="osmMap"><ZoomControl position="bottomright"/><Focus item={selected}/><TileLayer attribution='&copy; OpenStreetMap-bijdragers' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{algera.map(item=><Fragment key={item.id}><Polyline positions={item.route} pathOptions={{color:'#fff',weight:10,opacity:.88}}/><Polyline positions={item.route} pathOptions={{color:colors[item.status],weight:5,opacity:.9}}/></Fragment>)}<Marker position={[51.917,4.6006]} icon={algeraIcon(algera)} eventHandlers={{click:()=>onSelect(algera.find(i=>i.id==='algera-main')!)}}><Tooltip direction="top" offset={[0,-42]}><strong>Algerabrug</strong><br/>Tik voor actuele info</Tooltip></Marker>{others.map(item=><Fragment key={item.id}><Polyline positions={item.route} pathOptions={{color:'#fff',weight:9,opacity:.86}}/><Polyline positions={item.route} pathOptions={{color:colors[item.status],weight:5,opacity:.9,dashArray:item.status==='onbekend'?'8 9':undefined}}/><CircleMarker center={item.point} radius={10} pathOptions={{color:'#fff',weight:3,fillColor:colors[item.status],fillOpacity:1}} eventHandlers={{click:()=>onSelect(item)}}><Tooltip direction="top" offset={[0,-9]} permanent className="corridorLabel"><strong>{item.name}</strong><span>vaartijden</span></Tooltip></CircleMarker></Fragment>)}</MapContainer>}
