'use client';
import dynamic from 'next/dynamic';
import { useEffect,useMemo,useState } from 'react';
import { Bike,Camera,CarFront,ChevronRight,RefreshCw,Ship,X,ArrowLeftRight } from 'lucide-react';
import HlsCamera from './HlsCamera';
import { corridors,type Corridor,type CorridorStatus } from './corridors';
const MapView=dynamic(()=>import('./MapView'),{ssr:false,loading:()=> <div className="mapLoading">OpenStreetMap laden…</div>});
type LiveRoute={id:string;status:CorridorStatus;delayMinutes?:number|null;message:string;details?:string[]};
type LiveData={updatedAt:string;routes:LiveRoute[]};
type FerryItem={id:string;status:string};
type ViewItem=Corridor&{status:CorridorStatus;delayMinutes:number|null;message:string;details:string[]};
function icon(item:Corridor){if(item.id==='algera-lane')return <ArrowLeftRight/>;return item.mode==='fiets'?<Bike/>:item.mode==='water'?<Ship/>:<CarFront/>}
function delayStatus(delay:number|null):CorridorStatus{if(delay===null)return'onbekend';if(delay<5)return'groen';if(delay<15)return'oranje';return'rood'}
function scheduledNow(item:Corridor):CorridorStatus{if(!item.schedule)return'onbekend';const now=new Date();const day=now.getDay();const minutes=now.getHours()*60+now.getMinutes();const rows=item.schedule;const parse=(s:string)=>{const m=s.match(/(\d\d?):(\d\d)\s*[–-]\s*(\d\d?):(\d\d)/);return m?[+m[1]*60 + +m[2],+m[3]*60 + +m[4]]:null};let candidate:string|undefined;if(day>=1&&day<=5)candidate=rows.find(r=>/Ma–vr|Ma–za/.test(r.days))?.hours;else if(day===6)candidate=rows.find(r=>/^Za|Za,|Ma–za/.test(r.days))?.hours;else candidate=rows.find(r=>/Zo/.test(r.days))?.hours;if(!candidate||/Gesloten|aanvraag|Volgens/.test(candidate))return candidate?.includes('Gesloten')?'onbekend':'onbekend';const range=parse(candidate);return range&&minutes>=range[0]&&minutes<=range[1]?'groen':'onbekend'}
export default function Home(){
 const [live,setLive]=useState<LiveData|null>(null),[ferries,setFerries]=useState<FerryItem[]>([]),[selected,setSelected]=useState<ViewItem|null>(null),[loading,setLoading]=useState(false);
 async function load(){setLoading(true);try{const [a,b]=await Promise.all([fetch('/api/live',{cache:'no-store'}),fetch('/api/status',{cache:'no-store'})]);setLive(await a.json());setFerries((await b.json()).ferries??[])}finally{setLoading(false)}}
 useEffect(()=>{load();const t=setInterval(load,60000);return()=>clearInterval(t)},[]);
 const items=useMemo<ViewItem[]>(()=>corridors.map(c=>{const m=live?.routes?.find(r=>r.id===c.id);const delay=m?.delayMinutes??null;let status=c.kind==='weg'?delayStatus(delay):scheduledNow(c);const ferryId=c.id==='krimpen-lek'?'kinderdijk':c.id==='lekkerkerk'?'lekkerkerk':c.id==='ouderkerk'?'ouderkerk':null;const fs=ferryId?ferries.find(f=>f.id===ferryId)?.status:null;if(fs==='storing')status='rood';if(fs==='vaart')status='groen';return{...c,status,delayMinutes:delay,message:m?.message??(c.kind==='veer'?'Bekijk de vaartijden':'Geen betrouwbare live schatting'),details:m?.details??[]}}),[live,ferries]);
 const updated=live?.updatedAt?new Date(live.updatedAt).toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'}):'—';
 const algera=items.filter(i=>i.id.startsWith('algera'));
 return <main><header className="topbar"><div><span className="brand">KIO</span><h1>Krimpen in & uit</h1><p>Direct zien wat er bij brug en veren gebeurt</p></div><button onClick={load} aria-label="Vernieuwen"><RefreshCw className={loading?'spin':''}/></button></header>
 <section className="update"><span className="pulse"/> Bijgewerkt {updated}</section>
 <section className="mapCard"><div className="sectionHead"><div><span className="kicker">OPENSTREETMAP</span><h2>Uitgangen rond Krimpen</h2></div><span className="legend"><i className="green"/> 0–5 <i className="orange"/> 5–15 <i className="red"/> 15+ <i className="unknown"/> onbekend</span></div><MapView items={items} selected={selected} onSelect={setSelected}/><p className="mapHint">Tik op het bolletje van een corridor. Bij Algerabrug zoomt de kaart in op de actuele situatie.</p></section>
 <section><div className="sectionHead"><div><span className="kicker">ALGERABRUG</span><h2>Vertraging per doorgang</h2></div></div><div className="algeraSummary"><button className={`mainStatus ${algera[0]?.status??'onbekend'}`} onClick={()=>algera[0]&&setSelected(algera[0])}><span className="bigDot"/><b>Algerabrug</b><small>0–5 groen · 5–15 oranje · 15+ rood</small></button><div className="orbitDots">{algera.map(i=><button key={i.id} className={`orbit ${i.status}`} onClick={()=>setSelected(i)}><span>{icon(i)}</span><b>{i.delayMinutes===null?'?':i.delayMinutes===0?'0':`+${i.delayMinutes}`}</b><small>{i.id==='algera-bike'?'fiets':i.id==='algera-lane'?'wissel':'auto'}</small></button>)}</div></div></section>
 <section><div className="sectionHead"><div><span className="kicker">VEREN</span><h2>Status en vaartijden</h2></div></div><div className="corridorList">{items.filter(i=>i.kind==='veer').map(i=><button key={i.id} onClick={()=>setSelected(i)}><span className={`statusDot ${i.status}`}/><span className={`modeIcon ${i.status}`}>{icon(i)}</span><span><b>{i.name}</b><small>{i.subtitle}</small></span><span className="corridorTime"><b>Vaartijden</b></span><ChevronRight/></button>)}</div></section>
 <section><div className="sectionHead"><div><span className="kicker">LIVE CAMERA</span><h2>Algerabrug</h2></div><Camera/></div><HlsCamera/><p className="cameraNote">De stream loopt via de beveiligde KIO-proxy, zodat HLS ook werkt wanneer de bron geen browsertoegang toestaat.</p></section><footer>Kaartgegevens © OpenStreetMap-bijdragers · onbekende data blijft grijs</footer>
 {selected&&<div className="sheetBackdrop" onClick={()=>setSelected(null)}><aside className="detailSheet" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><span className={`statusBadge ${selected.status}`}>{selected.status==='groen'?'Groen':selected.status==='oranje'?'Oranje':selected.status==='rood'?'Rood':'Status onbekend'}</span><div className="detailTitle"><span className={`modeIcon ${selected.status}`}>{icon(selected)}</span><div><h2>{selected.name}</h2><p>{selected.subtitle}</p></div></div>{selected.kind==='weg'?<><div className="totalTime"><small>Actuele extra vertraging</small><strong>{selected.delayMinutes===null?'Geen betrouwbare schatting':selected.delayMinutes===0?'0 minuten':`+${selected.delayMinutes} minuten`}</strong></div><div className="situation"><b>Actuele verkeersinformatie</b><p>{selected.message}</p></div><div className="scaleExplain"><span className="green">0–5 min</span><span className="orange">5–15 min</span><span className="red">15+ min</span></div></>:<><div className="scheduleTitle"><small>DIENSTREGELING</small><h3>Vaartijden</h3></div><div className="scheduleTable">{selected.schedule?.map((r,index)=><div key={index}><span>{r.days}</span><b>{r.hours}</b>{r.note&&<small>{r.note}</small>}</div>)??<p>Geen vaartijden beschikbaar.</p>}</div>{selected.scheduleNote&&<p className="scheduleNote">{selected.scheduleNote}</p>}<p className="scheduleDisclaimer">Vaartijden kunnen bij storing, weer of feestdagen afwijken.</p></>}<div className="source">Laatste verkeerscontrole {updated}</div></aside></div>}
 </main>
}
