'use client';
import { AlertTriangle, Camera, ChevronRight, CircleHelp, Info, LockKeyhole, Menu, RefreshCw, Star, X, ShipWheel, Landmark } from 'lucide-react';
import { useCallback,useEffect,useMemo,useState } from 'react';
import HlsCamera,{type CameraFeed} from './HlsCamera';
type TrafficStatus='groen'|'oranje'|'rood'|'onbekend';
type RouteData={id:string;name:string;status:TrafficStatus;delayMinutes:number|null;updatedAt:string};
type Payload={updatedAt:string;cacheSeconds:number;source:string;routes:RouteData[];error?:string;diagnostics?:string[]};
const STATUS_COPY:Record<TrafficStatus,string>={groen:'Goede doorstroming',oranje:'Merkbare vertraging',rood:'Veel vertraging',onbekend:'Data tijdelijk onbekend'};
const HEADLINES=['Even kijken of de brug meewerkt…','Wordt het doorrijden of aansluiten?','Nog een slok koffie, of kun je gaan?','Kom je vandaag een beetje vlot weg?','De brug bepaalt weer de planning.'];
const BRIDGE_IDS=new Set(['cg-roosweg','industrieweg','nieuwe-tiendweg','boerhaavelaan','van-ostadelaan']);
const CAMERAS:CameraFeed[]=[{id:'GKR_01',name:'Algerabrug',description:'Overzicht Algerabrug'},{id:'GKR_02',name:'Algera Capelle',description:'Capelse zijde van de brug'},{id:'GKR_03',name:'Grote Kruispunt – Krimpen uit',description:'Verkeer dat Krimpen uit rijdt'},{id:'GKR_04',name:'Grote Kruispunt – Krimpen in',description:'Verkeer dat Krimpen in rijdt'}];
function ageLabel(date?:string){if(!date)return'Nog niet bijgewerkt';const m=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/60000));return m<1?'Zojuist bijgewerkt':m===1?'1 minuut geleden':`${m} minuten geleden`}
function phase(){const now=new Date();const slow=new Date('2026-07-20T00:00:00+02:00'),closed=new Date('2026-08-10T00:00:00+02:00'),end=new Date('2026-09-07T05:00:00+02:00');if(now>=closed&&now<end)return'closed';if(now>=slow&&now<closed)return'slow';if(now<slow)return'upcoming';return'after'}
export default function Home(){
 const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[selected,setSelected]=useState<RouteData|null>(null),[menuOpen,setMenuOpen]=useState(false),[helpOpen,setHelpOpen]=useState(false),[cameraOpen,setCameraOpen]=useState(false),[activeCamera,setActiveCamera]=useState<CameraFeed|null>(null),[bridgeOpen,setBridgeOpen]=useState(false),[worksOpen,setWorksOpen]=useState(false),[favoriteOpen,setFavoriteOpen]=useState(false),[favorite,setFavorite]=useState<string|null>(null),[now,setNow]=useState(Date.now()),[headline,setHeadline]=useState(HEADLINES[0]),[adminOpen,setAdminOpen]=useState(false),[adminCode,setAdminCode]=useState(''),[adminBusy,setAdminBusy]=useState(false),[adminMessage,setAdminMessage]=useState('');
 const loadTraffic=useCallback(async(silent=false,trigger=true)=>{if(!silent)setLoading(true);try{const r=await fetch(`/api/traffic?mode=${trigger?'trigger':'cache'}&t=${Date.now()}`,{cache:'no-store'});const p=await r.json() as Payload;if(!r.ok&&!p.routes?.length)throw new Error(p.error||'Niet beschikbaar');setData(p);return p}catch(e){if(!silent)setData({updatedAt:new Date().toISOString(),cacheSeconds:300,source:'error',routes:[],error:String(e)});return null}finally{if(!silent)setLoading(false)}},[]);
 useEffect(()=>{setHeadline(HEADLINES[Math.floor(Math.random()*HEADLINES.length)]);setFavorite(localStorage.getItem('kio-favorite-route'));void loadTraffic()},[loadTraffic]);
 useEffect(()=>{const id=setInterval(()=>{setNow(Date.now());void loadTraffic(true,false)},60000);return()=>clearInterval(id)},[loadTraffic]);
 const summary=useMemo(()=>{const r=data?.routes||[];return(r.some(x=>x.status==='rood')?'rood':r.some(x=>x.status==='oranje')?'oranje':r.length&&r.every(x=>x.status==='groen')?'groen':'onbekend') as TrafficStatus},[data]);
 const bridgeRoutes=(data?.routes||[]).filter(r=>BRIDGE_IDS.has(r.id));const ferryRoutes=(data?.routes||[]).filter(r=>!BRIDGE_IDS.has(r.id));const fav=(data?.routes||[]).find(r=>r.id===favorite);const worksPhase=phase();
 function saveFavorite(id:string|null){setFavorite(id);if(id)localStorage.setItem('kio-favorite-route',id);else localStorage.removeItem('kio-favorite-route');setFavoriteOpen(false)}
 async function choose(route:RouteData){const fresh=await loadTraffic(true,true);setSelected(fresh?.routes.find(r=>r.id===route.id)||route)}
 async function adminRefresh(){setAdminBusy(true);setAdminMessage('');try{const r=await fetch('/api/traffic',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:adminCode})});const p=await r.json() as Payload;if(!r.ok)throw new Error(p.error||'Mislukt');setData(p);setAdminMessage('Alle routes zijn vernieuwd.');setAdminCode('')}catch(e){setAdminMessage(e instanceof Error?e.message:'Mislukt')}finally{setAdminBusy(false)}}
 const cards=(routes:RouteData[])=>routes.map(route=><button className="routeCard" key={route.id} onClick={()=>void choose(route)}><span className={`routeSignal ${route.status}`}/><span className="routeMain"><strong>{route.name}</strong><small>{STATUS_COPY[route.status]}</small></span><span className="routeMetric"><strong>{route.delayMinutes===null?'—':route.delayMinutes===0?'Geen':`+${route.delayMinutes} min`}</strong><small>vertraging</small></span><ChevronRight size={20}/></button>);
 return <main className="shell"><section className="hero compactHero"><div className="brandRow"><div className="logo">K</div><button className="iconButton" onClick={()=>setMenuOpen(true)} aria-label="Menu"><Menu size={22}/></button></div><p className="eyebrow">KRIMPEN UIT</p><h1>{headline}</h1><div className={`overall ${summary}`}><span className="statusDot"/><span>{loading?'Verkeersbeeld ophalen…':STATUS_COPY[summary]}</span></div></section>
 <section className="content">
 {worksPhase!=='after'&&<button className={`worksBanner ${worksPhase}`} onClick={()=>setWorksOpen(true)}><AlertTriangle/><span><strong>{worksPhase==='closed'?'Algerabrug volledig afgesloten':worksPhase==='slow'?'Werkzaamheden op de Algerabrug':'Grote afsluiting komt eraan'}</strong><small>{worksPhase==='closed'?'Tot 7 september 05.00 uur':worksPhase==='slow'?'Versmalde rijstroken en 30 km/u':'Vanaf 10 augustus vier weken dicht'}</small></span><ChevronRight/></button>}
 {fav&&<><div className="sectionTitle mini"><div><p className="eyebrow dark">JOUW ROUTE</p><h2>Favoriet</h2></div></div><div className="routeList favoriteList">{cards([fav])}</div></>}
 <div className="sectionTitle"><div><p className="eyebrow dark">UITGAANDE ROUTES</p><h2>Kies jouw aanrijroute</h2></div><span className="updated" key={now}>{ageLabel(data?.updatedAt)}</span></div><div className="routeList">{loading?Array.from({length:5},(_,i)=><div className="routeCard skeleton" key={i}/>):cards(bridgeRoutes)}</div>
 <div className="sectionTitle ferryTitle"><div><p className="eyebrow dark">ALTERNATIEF OVER DE LEK</p><h2>Veerroutes</h2></div><ShipWheel size={22}/></div><div className="routeList">{!loading&&cards(ferryRoutes)}</div>
 <div className="trustNote"><CircleHelp size={18}/><p>Nieuwe TomTom-data wordt alleen opgehaald bij openen of aantikken als de gedeelde meting ouder is dan vijf minuten.</p><button onClick={()=>setHelpOpen(true)}><CircleHelp size={18}/></button></div></section>
 {menuOpen&&<div className="overlay" onClick={()=>setMenuOpen(false)}><aside className="sideMenu" onClick={e=>e.stopPropagation()}><div className="menuHead"><div><p className="eyebrow dark">KIO MENU</p><h2>Snel naar</h2></div><button className="close" onClick={()=>setMenuOpen(false)}><X/></button></div><button className="menuItem" onClick={()=>{setMenuOpen(false);setFavoriteOpen(true)}}><Star/><span><strong>Favoriete route</strong><small>Maximaal één, lokaal opgeslagen</small></span><ChevronRight/></button><button className="menuItem" onClick={()=>{setMenuOpen(false);setCameraOpen(true)}}><Camera/><span><strong>Verkeerscamera's</strong><small>Alle vier livebeelden</small></span><ChevronRight/></button><button className="menuItem" onClick={()=>{setMenuOpen(false);setBridgeOpen(true)}}><Landmark/><span><strong>Algerabrug</strong><small>Status en werkzaamheden</small></span><ChevronRight/></button><div className="menuDivider"/><button className="menuItem" onClick={()=>{setMenuOpen(false);setHelpOpen(true)}}><Info/><span><strong>Waarom elke vijf minuten?</strong><small>Over data en kosten</small></span><ChevronRight/></button><button className="menuItem adminMenu" onClick={()=>{setMenuOpen(false);setAdminOpen(true)}}><LockKeyhole/><span><strong>Beheer</strong><small>Handmatig vernieuwen</small></span><ChevronRight/></button></aside></div>}
 {favoriteOpen&&<div className="overlay" onClick={()=>setFavoriteOpen(false)}><article className="sheet" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setFavoriteOpen(false)}><X/></button><div className="helpIcon"><Star/></div><p className="eyebrow dark">PERSOONLIJK</p><h2>Favoriete route</h2><p className="detailStatus">Kies één route. Deze keuze blijft alleen op dit toestel staan.</p><div className="favoriteChoices"><button onClick={()=>saveFavorite(null)} className={!favorite?'active':''}>Geen favoriet</button>{(data?.routes||[]).map(r=><button key={r.id} onClick={()=>saveFavorite(r.id)} className={favorite===r.id?'active':''}>{r.name}</button>)}</div></article></div>}
 {bridgeOpen&&<div className="overlay" onClick={()=>setBridgeOpen(false)}><article className="sheet bridgeSheet" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setBridgeOpen(false)}><X/></button><div className="helpIcon"><Landmark/></div><p className="eyebrow dark">ALGERABRUG</p><h2>Bruginformatie</h2><div className="bridgeStatus"><span className="statusDot"/><div><strong>Live brugstatus</strong><small>Wordt in een volgende versie aan de officiële databron gekoppeld.</small></div></div><button className="worksLink" onClick={()=>{setBridgeOpen(false);setWorksOpen(true)}}><AlertTriangle/><span><strong>Werkzaamheden 2026</strong><small>Bekijk alle belangrijke data</small></span><ChevronRight/></button></article></div>}
 {worksOpen&&<div className="overlay" onClick={()=>setWorksOpen(false)}><article className="sheet worksSheet" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setWorksOpen(false)}><X/></button><div className="helpIcon warning"><AlertTriangle/></div><p className="eyebrow dark">PLANNING 2026</p><h2>Werkzaamheden Algerabrug</h2><div className="timeline"><div><b>19 – 23 juli</b><strong>Nachtafsluitingen</strong><p>Vier nachten gesloten van 22.00 tot 05.00 uur. Auto’s worden omgeleid via Gouda.</p></div><div><b>20 juli – 9 augustus</b><strong>Versmalde rijstroken</strong><p>Hoofdrijbaan en wisselstrook zijn smaller. Maximumsnelheid 30 km/u.</p></div><div><b>20 juli – 21 september</b><strong>Tijdelijke fiets- en voetgangersbrug</strong><p>Voor fietsers en voetgangers blijft een aparte tijdelijke verbinding beschikbaar.</p></div><div className="critical"><b>10 augustus – 7 september</b><strong>Vier weken volledig dicht</strong><p>De Algerabrug is afgesloten voor autoverkeer en openbaar vervoer tot maandag 7 september 05.00 uur.</p></div></div><p className="muted">Tijdens de afsluiting zet KIO de veerroutes extra prominent in beeld.</p></article></div>}
 {cameraOpen&&<div className="overlay cameraOverlayPage" onClick={()=>{setCameraOpen(false);setActiveCamera(null)}}><section className="cameraSheet" onClick={e=>e.stopPropagation()}><div className="menuHead"><div><p className="eyebrow dark">LIVEBEELD</p><h2>Verkeerscamera's</h2></div><button className="close" onClick={()=>{setCameraOpen(false);setActiveCamera(null)}}><X/></button></div>{!activeCamera?<div className="cameraChoices">{CAMERAS.map(c=><button key={c.id} className="cameraChoice" onClick={()=>setActiveCamera(c)}><span className="cameraIcon"><Camera/></span><span><strong>{c.name}</strong><small>{c.description}</small></span><em>Bekijk live</em></button>)}</div>:<HlsCamera camera={activeCamera} onClose={()=>setActiveCamera(null)}/>}</section></div>}
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><article className="sheet" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><div className={`sheetStatus ${selected.status}`}/><p className="eyebrow dark">ROUTEDETAIL</p><h2>{selected.name}</h2><p className="detailStatus">{STATUS_COPY[selected.status]}</p><div className="metrics"><div><RefreshCw/><span><small>Actuele vertraging</small><strong>{selected.delayMinutes===null?'Onbekend':selected.delayMinutes===0?'Geen vertraging':`+${selected.delayMinutes} minuten`}</strong></span></div></div><p className="sheetUpdated">{ageLabel(selected.updatedAt)} · TomTom</p></article></div>}
 {helpOpen&&<div className="overlay" onClick={()=>setHelpOpen(false)}><article className="sheet helpSheet" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setHelpOpen(false)}><X/></button><div className="helpIcon"><CircleHelp/></div><h2>Waarom elke vijf minuten?</h2><p>Alle bezoekers delen dezelfde TomTom-meting. Alleen bij openen of aantikken wordt gecontroleerd of een nieuwe meting nodig is.</p></article></div>}
 {adminOpen&&<div className="overlay" onClick={()=>setAdminOpen(false)}><article className="sheet adminSheet" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setAdminOpen(false)}><X/></button><h2>Handmatig vernieuwen</h2><label className="codeLabel">Admincode</label><input className="codeInput" value={adminCode} onChange={e=>setAdminCode(e.target.value)} type="password"/><button className="adminButton" disabled={adminBusy||!adminCode} onClick={()=>void adminRefresh()}>{adminBusy?<RefreshCw className="spin"/>:<RefreshCw/>} Vernieuwen</button>{adminMessage&&<p className="adminMessage">{adminMessage}</p>}</article></div>}
 </main>}
